services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=leoplay_db'
      - 'POSTGRES_PASSWORD=admin_leoplay_db'
      - 'POSTGRES_USER=admin_leoplay_db'
    ports:
      - '5432:5432'
    volumes:
      - v_postgres_data:/var/lib/postgresql/data
volumes:
  v_postgres_data:
    external: true