services:
  postgres:
    image: 'postgres:17-alpine'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=leoplay_db'
      - 'POSTGRES_USER=admin_leoplay_db'
      - 'POSTGRES_PASSWORD=admin_leoplay_db'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
