spring.application.name=leoplay
server.port=8090
server.servlet.context-path=/leo-play/api/

langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY:demo}
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini